name: example_gui
description: Example additional GUI tools
events:
    close_me:
        payload: ~
widgets:
    my_generic:
        type: primitive
        attributes:
            title: text
        children:
            body: ~
        events: [example_gui.close_me, example_gui.collapse_me]
